## A basic GitHub Actions workflow for your Quarkus application.

name: CI build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw package -Dmaven.test.skip
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: convert github repository name to lowercase
      run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/main/docker/Dockerfile.jvm
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}-api:latest
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}-api:latest
        cache-to: type=inline
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./src/main/demo-frontend
        file: ./src/main/demo-frontend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:latest
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:latest
        cache-to: type=inline
    
